### ISSUE TITLE
oryx2.20 bug bug bug

### ISSUE THREAD

**Issue by flyingandrunning** [OryxProject/oryx#311] opened 2016-09-08 05:51 UTC
16/09/08 13:37:51 INFO als.ALSSpeedModelManager: Loading new model
16/09/08 13:37:51 INFO als.ALSSpeedModelManager: Updating model
16/09/08 13:37:51 ERROR speed.SpeedLayer: Error while consuming updates
java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.String
	at net.openhft.koloboke.collect.impl.hash.MutableLHashParallelKVObjObjMapGO.removeIf(MutableLHashParallelKVObjObjMapGO.java:1143)
	at com.cloudera.oryx.app.als.FeatureVectors.retainRecentAndIDs(FeatureVectors.java:133)
	at com.cloudera.oryx.app.speed.als.ALSSpeedModel.retainRecentAndUserIDs(ALSSpeedModel.java:101)
	at com.cloudera.oryx.app.speed.als.ALSSpeedModelManager.consume(ALSSpeedModelManager.java:123)
	at com.cloudera.oryx.lambda.speed.SpeedLayer.lambda$start$1(SpeedLayer.java:125)
	at com.cloudera.oryx.common.lang.LoggingCallable.lambda$log$0(LoggingCallable.java:48)
	at com.cloudera.oryx.common.lang.LoggingCallable.lambda$asRunnable$1(LoggingCallable.java:66)
	at java.lang.Thread.run(Thread.java:745)
16/09/08 13:37:51 INFO speed.SpeedLayer: Shutting down model manager
16/09/08 13:37:51 INFO speed.SpeedLayer: Shutting down consumer

Have a question? ask at https://groups.google.com/a/cloudera.org/forum/#!forum/oryx-user instead!

Have a look at the "guidelines for contributing" link above.

Please provide basic information like version of Oryx, how you ran the binaries, error messages
of any kind, and relevant parts of the configuration file.

Delete this text.

**Comment by cimox** [comment] 2016-09-09 09:23
Is this really bug of Oryx? How do you ingest data, through serving layer? I've got this exception as well, but only when I was ingesting data directly to Kafka input topics using wrong format.

**Comment by srowen** [comment] 2016-09-09 17:49
Hm! this is a duplicate of https://github.com/OryxProject/oryx/issues/304, so maybe we can continue there? it's good news actually if others can reproduce it.

**Closed by srowen** 2016-09-09 17:49 UTC
