### ISSUE TITLE
oryx 2.2.x  serving layer -function for /similarity

### ISSUE THREAD

**Issue by flyingandrunning** [OryxProject/oryx#316] opened 2016-09-14 08:58 UTC
hi srowen
    have problem for url /similarity , but result is :
         ObjectId(56151b30616721f977af5cb1),Infinity
        ObjectId(576c8d526a4070df4ec709a4),Infinity
        ObjectId(56e1a0bdfafd1fe556167237),Infinity
        ObjectId(566839d0fbb0ab9b4bd6f94b),Infinity
        ObjectId(534ac9cc5275f372280003d5),Infinity
        ObjectId(56a2e54f27b88040780d9433),Infinity
        ObjectId(53fb235c3aa571f2051c6987),Infinity
        ObjectId(5763adf3aad9d7c4771b30bb),Infinity
       ObjectId(52836252dfd45916330528ed),Infinity
       ObjectId(574ab4f23a906d6552aba210),Infinity
can you give me some information about the /similarity api
 
the project info is :
test dataset is 460000 event.
user size is 20000000.
item siez is 1400000.

**Comment by srowen** [comment] 2016-09-15 08:04
I believe this means that some vector has a very very small norm (not 0 or else I'm pretty sure we'd have NaN and those won't be returned). That's an unusual problem, and often means something is kind of wrong with the data, but not impossible. 

Can you say any more about your data, your model, your settings?

The problem is, however, that no matter what this is an invalid result from this API because the result is a cosine similarity which should be in [-1,1]. I will look into how this could happen and figure out how to handle this.

**Comment by srowen** [comment] 2016-09-15 09:26
@flyingandrunning what version are you running BTW? I can't reproduce this no matter what input I pass, but, it may have been fixed by https://github.com/OryxProject/oryx/commit/ed19d4589c80e6cec0ce7719a29acfc561755e79 actually, which isn't released.

**Comment by flyingandrunning** [comment] 2016-09-18 08:39
i am so sorry,you're right. i found that dataset has a very very small,but user dataset is too big.

**Comment by hantuzun** [comment] 2016-09-19 12:15
@flyingandrunning are there too many users compared to items?

**Comment by srowen** [comment] 2016-09-19 13:39
@flyingandrunning you might have a real problem here, can you say more about your input? how many features? how many users and items?

**Comment by hantuzun** [comment] 2016-09-19 14:34
@srowen; the top comment has relevant sizes now. thanks @flyingandrunning!

Note that the number of items and users are much bigger than the actions given.

Cos similarity is undefined when at least one of the vectors is a zero vector. Is it the case here? ALS should start computing begin with randomized vectors.

**Comment by srowen** [comment] 2016-09-20 18:24
This would only happen at scoring time, not a model build time. Even with a zero vector you should get NaN at worst, not infinity. This could be a round-off problem with very very small vectors. I think my change at https://github.com/OryxProject/oryx/commit/ed19d4589c80e6cec0ce7719a29acfc561755e79 would improve this. Let's reopen if it's still happening on a build with that commit, but I was unable to imagine or reproduce this situation locally.

**Closed by srowen** 2016-09-20 18:24 UTC
